server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qyy_db?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  quartz:
    job-store-type: jdbc #持久化到数据库
    properties:
      org:
        quartz:
          datasource:
            # 新版驱动从com.mysql.jdbc.Driver变更为com.mysql.cj.jdbc.Driver
            driver-class-name: com.mysql.cj.jdbc.Driver
            # 数据源需要添加时间标准和指定编码格式解决乱码 You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.
            url: jdbc:mysql://localhost:3306/qyy_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
            username: root
            password: root
          scheduler:
            instancName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate #StdJDBCDelegate说明支持集群
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 1000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 20
            threadPriority: 5
    druid:
      aop-patterns: com.atguigu.admin.*  #springbean监控
      filters: stat,wall,slf4j  #所有开启的功能

      stat-view-servlet:  #监控页配置
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter:  #web监控
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


      filter:
        stat: #sql监控
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall: #防火墙
          enabled: true
          config:
            drop-table-allow: false

  redis:
    host: 127.0.0.1
    port: 6379
    client-type: jedis
logging:
  #在Spring Boot项目中默认加载类路径下的logback-spring.xml文件
  config: classpath:logback-spring.xml


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为0)
      # 若逻辑已删除和未删除的值和默认值一样，则可以不配置这2项

#  mapper-locations: /mapper/*
#
#
#  redis:
#    host: r-bp1nc7reqesxisgxpipd.redis.rds.aliyuncs.com
#    port: 6379
#    password: lfy:Lfy123456
#    client-type: jedis
#    jedis:
#      pool:
#        max-active: 10
#  #    url: redis://lfy:Lfy123456@r-bp1nc7reqesxisgxpipd.redis.rds.aliyuncs.com:6379
#  #    lettuce:
#  #      pool:
#  #        max-active: 10
#  #        min-idle: 5
#
#
#
#  #    type: com.zaxxer.hikari.HikariDataSource
#  jdbc:
#    template:
#      query-timeout: 3
#  boot:
#    admin:
#      client:
#        url: http://localhost:8888
#        instance:
#          prefer-ip: true  #使用ip注册进来
#  application:
#    name: boot-05-web-admin
#
#
#
#
## 配置mybatis规则、使用MyBatisPlus则此项配置无效
##mybatis:
###  config-location: classpath:mybatis/mybatis-config.xml
##  mapper-locations: classpath:mybatis/mapper/*.xml
##  configuration:  # 指定mybatis全局配置文件中的相关配置项
##    map-underscore-to-camel-case: true
#
#
## management 是所有actuator的配置
## management.endpoint.端点名.xxxx  对某个端点的具体配置
#management:
#  endpoints:
#    enabled-by-default: true  #默认开启所有监控端点  true
#    web:
#      exposure:
#        include: '*' # 以web方式暴露所有端点
#
#  endpoint:   #对某个端点的具体配置
#    health:
#      show-details: always
#      enabled: true
#
#    info:
#      enabled: true
#
#    beans:
#      enabled: true
#
#    metrics:
#      enabled: true
#
#info:
#  appName: boot-admin
#  appVersion: 1.0.0
#  mavenProjectName: @project.artifactId@
#  mavenProjectVersion: @project.version@
#
#
#
#mybatis 配置 映射文件路径
#mybatis:
##  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true

